# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure Telegraf path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ telegraf_uid }}"
    group: "{{ telegraf_gid }}"
  with_items:
    - {path: "{{ telegraf_base_path }}", when: true}

- name: Ensure Telegraf support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ telegraf_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ telegraf_uid }}"
    group: "{{ telegraf_gid }}"
  with_items:
    - env

- name: Ensure Telegraf network is created in Docker
  community.docker.docker_network:
    name: "{{ telegraf_container_network }}"
    driver: bridge

- name: Ensure Telegraf container image is pulled
  community.docker.docker_image:
    name: "{{ telegraf_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure telegraf.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/telegraf.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ telegraf_identifier }}.service"
    mode: 0644
