# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Telegraf installation tasks
  when: telegraf_enabled | bool
  tags:
    - setup-all
    - setup-telegraf
    - install-all
    - install-telegraf
  block:
    - name: Validate Telegraf configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Telegraf
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Telegraf uninstallation tasks
  when: not telegraf_enabled | bool
  tags:
    - setup-all
    - setup-telegraf
  block:
    - name: Uninstall Telegraf
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
